// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XaRGwjGCVlD33-mNGqGkiqOjjgxZ4q0',
    appId: '1:749709458083:web:0286f16c1b8fc37bb29d16',
    messagingSenderId: '749709458083',
    projectId: 'levelup-by-telkom',
    authDomain: 'levelup-by-telkom.firebaseapp.com',
    storageBucket: 'levelup-by-telkom.appspot.com',
    measurementId: 'G-9GL6ZRM55R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELChkroXkk9VjTvfSGixuYHpFGOwCoPs',
    appId: '1:749709458083:android:3cacb13410a24a3cb29d16',
    messagingSenderId: '749709458083',
    projectId: 'levelup-by-telkom',
    storageBucket: 'levelup-by-telkom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuyN5C5Hq6I5T3ba6ClMBal2GNDBFy3g',
    appId: '1:749709458083:ios:93a4d1a5d5fe88b1b29d16',
    messagingSenderId: '749709458083',
    projectId: 'levelup-by-telkom',
    storageBucket: 'levelup-by-telkom.appspot.com',
    iosBundleId: 'com.example.levelupId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuyN5C5Hq6I5T3ba6ClMBal2GNDBFy3g',
    appId: '1:749709458083:ios:bd22868714aacd4bb29d16',
    messagingSenderId: '749709458083',
    projectId: 'levelup-by-telkom',
    storageBucket: 'levelup-by-telkom.appspot.com',
    iosBundleId: 'com.example.levelupId.RunnerTests',
  );
}
